require: rubocop-rails

AllCops:
  TargetRubyVersion: 2.5
  Exclude:
    - vagrant/**/*
    - script/*_temp.rb

Lint/RedundantCopDisableDirective:
  Enabled: false

Lint/RedundantSplatExpansion:
  Enabled: false

Lint/SendWithMixinArgument:
  Enabled: false

Rails:
  Enabled: true

Rails/ActiveRecordAliases:
  Enabled: false

Rails/DynamicFindBy:
  Enabled: false

Rails/EnumHash:
  Enabled: false

Rails/FilePath:
  Enabled: false

Rails/HasAndBelongsToMany:
  Enabled: false

Rails/HasManyOrHasOneDependent:
  Enabled: false

Rails/HelperInstanceVariable:
  Enabled: false

Rails/InverseOf:
  Enabled: false

Rails/LexicallyScopedActionFilter:
  Enabled: false

Rails/OutputSafety:
  Enabled: false

Rails/RakeEnvironment:
  Enabled: false

Rails/SkipsModelValidations:
  Enabled: false

Rails/UnknownEnv:
  Enabled: false

Style/FormatStringToken:
  Enabled: false

Metrics/LineLength:
  Max: 120

Metrics/BlockLength:
  Exclude:
    - lib/tasks/*
    - lib/tasks/*/*
    - app/*/concerns/*.rb
    - app/views/*/*.xml.builder
    - app/views/*/*.json.jbuilder
    - app/views/*/*/*.xml.builder
    - app/admin/*
    - app/views/admin/*/*.html.arb

Lint/ScriptPermission:
  Exclude:
    - script/*

Style/Documentation:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Naming/AccessorMethodName:
  Enabled: false

Style/PerlBackrefs:
  Enabled: false

Style/RegexpLiteral:
  Enabled: false

Style/EmptyCaseCondition:
  Description: 'Avoid empty condition in case statements.'
  Enabled: false
