chart: {}
title:
credits:
  enabled: false
plotOptions:
  pie:
    colors: [
      '#99dde3',
      '#a2a8b3',
      '#7b559b',
      '#33bbc6',
      '#008893'
    ]
    allowPointSelect: true
    cursor: pointer
    dataLabels:
      enabled: true
      color: '#000000'
      connectedColor: '#000000'
series:
  - type: pie
    name: piedata
